---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team6-eureka-client-loans
  namespace: group1-team6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team6-eureka-client-loans
  template:
    metadata:
      labels:
        app: team6-eureka-client-loans
    spec:
      containers:
      - name: team6-eureka-client-loans
        image: k8s-vga-worker1:5000/group1-team6-eureka-client-loans:v0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: team6-eureka-client-loans
  namespace: group1-team6
spec:
  selector:
    app: team6-eureka-client-loans
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30614
  type: NodePort
